### ISSUE TITLE
sleep before swith to next page

### ISSUE THREAD

**Issue by love1900905** [Sec-ant/weread-scraper#1] opened 2022-10-08 18:25 UTC
First of all, many thanks for this great script!

but sometimes the script failed, especially when scraping for book which have maaaaaaaaaany pages, e.g. a suite book which have 1000+ pages.
Looks weread have rate limit and if there are too quickly GET for many pages, it will report the book is not accessable (for a while).

So, could you please add a sleep (e.g. 0.1 second) before go to nextPage?

**Comment by Sec-ant** [comment] 2022-10-09 15:54
Good suggestion. I added another option called "Set Click Interval" as a GM menu command, where you can input a sleep interval value (in milliseconds, default to 0). Yet this feature will break the script's normal function in Chrome or MS Edge and is only tested to be good in Firefox, so I created [another branch](https://github.com/Sec-ant/weread-scraper/tree/with-click-interval) for it. If a solution in Chrome or MS Edge is found I'll merge it back to main.

The issue encountered in Chrome etc. is that you cannot programmatically trigger a click event on the next page button when everything is settled because of "sleeping". And FWIK this problem is roughly caused by some Weread script attempting to acquire the stack trace information of the click event while the userscript running in Chrome will produce an error during this procedure:
![image](https://user-images.githubusercontent.com/10386119/194766275-1404182a-e2bd-4283-b251-3ccb0726040a.png)
which will further introduce an uncaught error to prevent next page from loading
![image](https://user-images.githubusercontent.com/10386119/194766326-4a9af01b-455a-4838-b21d-6d764fdf8a03.png)

With the debugger loop obfuscation, it is extremely hard to debug the code in chrome, and I haven't found a solution so far, so any help is welcomed ❤️

**Comment by love1900905** [comment] 2022-10-10 03:50
Thanks for the update. 

I love Chrome and not use FF  :)
here is my work around for Chorme. It's kind of waste CPU, but weread script can "detect" we did spend some time on reading this book :)

1) add a "sleep" function
```
//  function sleep(ms) {  // not working. MutationObserver or Tampermonkey does not support asnyc?
//    return new Promise(_r => setTimeout(_r, ms));
//  }

  //https://www.codegrepper.com/code-examples/javascript/sync+sleep+js
    function sync_sleep_ms(milliseconds) {
        const date = Date.now();
        let currentDate = null;
        do {
            currentDate = Date.now();
            // pure "empty" loop is greedy, and waste CPU, also, weread script still think 0 minutes spent on this book
            // by adding this random mouse move, weread script can "detect" we did spend some time on reading this book :)
            bodyElement.dispatchEvent(
                new MouseEvent("move", {
                    clientX: currentDate % 199,
                    clientY: currentDate % 299,
                })
            );
        } while (currentDate - date < milliseconds);
    }
```

2) in the contentObserver, call "sleep"
```
    if (contentFound && nextPage) {
      contentFound = false;
      //sleep(1 * 1000); // sleep 1 seconds per page (rate limit)  // async is not supported.
      sync_sleep_ms(1000);                    // <=============== add this line to "sleep"
      nextPage.dispatchEvent(
          new MouseEvent("click", {
              clientX: 1,
              clientY: 1,
          })
```

**Comment by Sec-ant** [comment] 2022-10-10 05:15
Ok, thanks for the tips, I think I over overcomplified things. I find it won't work if the click `dispatchEvent` is put into a timeout handler but will work well if it runs outside of the handler. Async is supported as long as you use `await` to wait for the promise and wrap it in an `async` function. The branch is merged back to main and this sleep feature is now supported in Chrome, MS Edge and FF. Feel free to open this issue again in case you find it problematic.

As for books with 1000+ pages, if the sleep time is too long, you can also try splitting the book into several segments and using the "Stop Scraping & Save" option to save them, and then merge them back manually. This requires some hands-on tweaks but will save you some time if the book has too many pages. If you can provide a free example with such many pages, I will look further into it.

**Closed** 2022-10-10 05:14 UTC
Labels: enhancement, help wanted, good first issue
